### ISSUE TITLE
请问查询命令能否简写呢？

### ISSUE THREAD

**Issue by mmmjie** [KoishiMoe/nonebot-plugin-mediawiki#1]
感谢作者的分享
 我打算在游戏群中使用，
但查项目的时候需要输入[[]]这个不是很方便
是否可以wikixxx
如wiki大凤

这样会方便很多，手机QQ也方便输入，wiki的前缀一般也不会误触

**Comment by mmmjie** [comment]
习惯了感觉也还好

**Comment by KoishiMoe** [comment]
az，我已经开始写了

**Comment by mmmjie** [comment]
> 

修改后的我已经用上了，非常好用！！
真是感激不尽

我也是发送后觉得要麻烦您，所以不大好意思，就关闭了
没想到这么快
大佬真是太强了！！！！！！

**Comment by KoishiMoe** [comment]
该功能已经在最新版本中实现，因此我将关闭该issue，如果该功能出了什么bug，还请另开issue提交

**Comment by KoishiMoe** [comment]
另外就是我觉得吧，确实能让软件更好用的issue就没必要主动关，毕竟项目维护者真觉得很麻烦的话也是可以直接关掉的😜
