### ISSUE TITLE
Windows环境下使用截图功能会抛出NotImplementedError

### ISSUE THREAD

**Issue by niucattle** [KoishiMoe/nonebot-plugin-mediawiki#4]
![9a45b73509a97b7ab23d57749004962b](https://github.com/KoishiMoe/nonebot-plugin-mediawiki/assets/118875129/eac848d1-ef3a-4903-9089-1661dd99dfa7)
python3.10
截图就报这错 playwright和chromium都装了
单装了个这个插件

**Comment by niucattle** [comment]
> ![9a45b73509a97b7ab23d57749004962b](https://private-user-images.githubusercontent.com/118875129/345832552-eac848d1-ef3a-4903-9089-1661dd99dfa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTg3NDMsIm5iZiI6MTcyMDA5ODQ0MywicGF0aCI6Ii8xMTg4NzUxMjkvMzQ1ODMyNTUyLWVhYzg0OGQxLWVmM2EtNDkwMy05MDg5LTE2NjFkZDk5ZGZhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxMzA3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDYwYmFjYzdhZmM2NDU0Nzc3MjRiNTY2ZWZjOGFiN2Q3MmRhNmY4NmE1NmFkYTRmMTBmMGRjODUyZTU4MDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kNZlEcePqpSs3CcOeibcUibCEdyMedMq4iBJzWR-lcQ) python3.10 截图就报这错 playwright和chromium都装了 单装了个这个插件

版本1.1.0a2

**Comment by KoishiMoe** [comment]
nonebot用的`uvicorn`在Windows上和`playwright`冲突，我这边无法解决

有两个方案，供参考：
1. （推荐）在你的机器人中，关闭fastapi的`fastapi_reload`，或者直接换个驱动器。参考 https://nonebot.dev/docs/advanced/driver#fastapi%E9%BB%98%E8%AE%A4 
2. 用linux跑（可以考虑wsl）

**Comment by niucattle** [comment]
emm 具体怎么关fastapi_reload呢  我用的原版nonebot2
