### ISSUE TITLE
大佬可以兼容下最新版nb2吗

### ISSUE THREAD

**Issue by mmmjie** [KoishiMoe/nonebot-plugin-mediawiki#5]
好像部分人是旧版pydantic 1，部分人pydantic 2

出个分叉兼容pydantic2和最新版nb2？

感谢作者的分享，插件帮助了很多人

**Comment by mmmjie** [comment]
提供下16个月这个插件的调用次数
![ae457f2fdf4b080bf2a66094c5d8a3b3](https://github.com/user-attachments/assets/fda2df60-73e3-4d9b-88f0-5050241c7d48)

差一点8W次

**Comment by mmmjie** [comment]
> 提供下16个月这个插件的调用次数 ![ae457f2fdf4b080bf2a66094c5d8a3b3](https://private-user-images.githubusercontent.com/45615222/355752926-fda2df60-73e3-4d9b-88f0-5050241c7d48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjIzNjgsIm5iZiI6MTcyMzAyMjA2OCwicGF0aCI6Ii80NTYxNTIyMi8zNTU3NTI5MjYtZmRhMmRmNjAtNzNlMy00ZDliLTg4ZjAtNTA1MDI0MWM3ZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA5MTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmY2Q0YjVjNDQzOTc4Njg0ZjM1ZTVhMWYyYjU0OTcwOTRlYWM1YTNkOGI0M2VlZGUyODNmODk5Mzc4NzBmZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.usI2021EWVC0Xuh5sU6fkRhu_m0KQXdC9n-Qc68oCqI)
> 
> 差一点8W次

好像不止。。。中间几次因为数据有问题清空过，估计有20W+了

**Comment by KoishiMoe** [comment]
周末我看看

**Comment by mmmjie** [comment]
> 周末我看看

爱你❤

**Comment by KoishiMoe** [comment]
[nonebot_plugin_mediawiki-1.1.1-py3-none-any.whl.zip](https://github.com/user-attachments/files/16574245/nonebot_plugin_mediawiki-1.1.1-py3-none-any.whl.zip)
试试这个？我这边没有测试环境了，看上游更新日志应该没有什么破坏性更改会影响这个插件

**Comment by mmmjie** [comment]
> [nonebot_plugin_mediawiki-1.1.1-py3-none-any.whl.zip](https://github.com/user-attachments/files/16574245/nonebot_plugin_mediawiki-1.1.1-py3-none-any.whl.zip) 试试这个？我这边没有测试环境了，看上游更新日志应该没有什么破坏性更改会影响这个插件

抱歉，之前电脑出问题了，所以没环境测试

现在我试了一下可以了。感谢大佬

**Comment by KoishiMoe** [comment]
这个串我先关了，如果发现在新版nb上有什么旧版不存在的bug还请报告一下，~~我这边基本不用bot了，所以大概很难自己发现~~

**Comment by devil233-ui** [comment]
> 这个串我先关了，如果发现在新版nb上有什么旧版不存在的bug还请报告一下，~我这边基本不用bot了，所以大概很难自己发现~

2.4.2还能战，不过上来就自顾自卸载掉装上2.3.3有点难崩，建议优化下（
另外还有一个问题我就单独开了。
![Image](https://github.com/user-attachments/assets/c126a81b-88d2-4d11-967c-c02fef2eeb4d)
![Image](https://github.com/user-attachments/assets/b544e3b2-6ee8-4796-a6ce-2b0667dce9a1)

**Comment by KoishiMoe** [comment]
> > 这个串我先关了，如果发现在新版nb上有什么旧版不存在的bug还请报告一下，~我这边基本不用bot了，所以大概很难自己发现~
> 
> 2.4.2还能战，不过上来就自顾自卸载掉装上2.3.3有点难崩，建议优化下（ 另外还有一个问题我就单独开了。 ![Image](https://github.com/user-attachments/assets/c126a81b-88d2-4d11-967c-c02fef2eeb4d) ![Image](https://github.com/user-attachments/assets/b544e3b2-6ee8-4796-a6ce-2b0667dce9a1)

那个确实，依赖版本卡的比较死……我写这个插件的时候nb2经常破坏性更改所以有点ptsd……我稍后重发个版本把限制拿掉

第二张图看起来不像是本插件的问题？如果是装了本插件之后才出现的，那可能是nb2被降版本破坏了其他插件的功能🤔

所以另一个问题是？我看看能不能一块修了

**Comment by devil233-ui** [comment]
哦不好意思没说清楚，图二是被降到2.3.3后我的所有插件几乎都无法载入，以及完全无法启动。
~~发了两个问题~~
